sudo: required
language: generic
services:
        - docker

before_install:
        - docker build -t syacussi/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true syacussi/react-test npm test

after_success:
        - docker build -t syacussi/multi-client ./client
        - docker build -t syacussi/multi-nginx ./nginx
        - docker build -t syacussi/multi-server ./server
        - docker build -t syacussi/multi-worker ./worker
        # Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
        #take those images and push them to docker hub
        - docker push syacussi/multi-client
        - docker push syacussi/multi-nginx
        - docker push syacussi/multi-server
          docker push syacussi/multi-worker
